Repository yoonc01/Fandom-K, pull requests merged in 2025-01, with the labels that each got.

#42 Feat/#10/intro section layout
  .gitignore
  .vscode/settings.json
  package-lock.json
  package.json
  src/App.jsx
  src/assets/icons/FandomKLogo.svg
  src/assets/images/introSectionIdolImage.png
  src/assets/images/leftTopGradient.png
  src/pages/landingPage/IntroSection.jsx
  src/pages/landingPage/LandingPage.jsx
  tailwind.config.js
Labels: enhancement

#41 Feat : #11 로컬스토리지 제작
  src/utils/CreditStorage.js
Labels: enhancement

#46 Feat/#25/primary button
  index.html
  src/components/PrimaryButton.jsx
  src/pages/landingPage/IntroSection.jsx
Labels: enhancement

#47 Feat/#30/donation card
  src/App.jsx
  src/assets/icons/donation_credit.svg
  src/main.jsx
  src/pages/list/DonationCard.jsx
  src/pages/list/DonationsList.jsx
  src/pages/list/ListPage.jsx
Labels: enhancement

#49 Refactor/#30/donation card
  src/App.jsx
  src/assets/icons/Credit.svg
  src/pages/list/DonationCard.jsx
  src/pages/list/DonationsList.jsx
  src/pages/list/ListPage.jsx
Labels: enhancement

#54 feat : #53/Commit types 추가 및 Readme update
  README.md
Labels: documentation

#58 Feat: #31/donations list 레이아웃
  src/assets/icons/nextIcon.svg
  src/assets/icons/prevIcon.svg
  src/pages/listPage/DonationCard.jsx
  src/pages/listPage/DonationsList.jsx
  src/pages/listPage/ListPage.jsx
Labels: enhancement

#56 Feat: #55/introSection의 버튼과 로고에 클릭 이벤트 추가
  src/pages/landingPage/IntroSection.jsx
Labels: enhancement

#65 feat : #26/Modal component 구현
  src/assets/icons/closeButton.svg
  src/components/Modal.jsx
Labels: enhancement

#66 Design: #32/donation card 반응형 디자인 구현
  src/pages/listPage/DonationCard.jsx
  src/pages/listPage/DonationsList.jsx
Labels: enhancement

#67 Design: #33/donations list 반응형 디자인 구현
  src/pages/listPage/DonationCard.jsx
  src/pages/listPage/DonationsList.jsx
Labels: enhancement

#69 feat: Header component done
  src/components/Header.jsx
Labels: enhancement

#79 Feat/#35/donation modal
  src/assets/icons/Credit.svg
  src/assets/icons/creditLight.svg
  src/components/Header.jsx
  src/pages/listPage/CreditSection.jsx
  src/pages/listPage/DonationCard.jsx
  src/pages/listPage/DonationModalContent.jsx
  src/pages/listPage/DonationsList.jsx
  src/pages/listPage/ListPage.jsx
  src/pages/listPage/MonthlyChart.jsx
Labels: enhancement

#81 fix : #80/Primary Button의 style prop을 className prop으로 변경
  src/components/PrimaryButton.jsx
  src/pages/landingPage/IntroSection.jsx
  src/pages/listPage/CreditShortageModalContent.jsx
  src/pages/listPage/DonationCard.jsx
  src/pages/listPage/DonationModalContent.jsx
  src/pages/listPage/MonthlyChart.jsx
  src/pages/listPage/RechgModalContent.jsx
Labels: fix

#85 Feat: #34/DonationsList 컴포넌트 API 연결
  package-lock.json
  package.json
  src/apis/donationApi.js
  src/main.jsx
  src/pages/listPage/DonationCard.jsx
  src/pages/listPage/DonationsList.jsx
Labels: enhancement
