Repository yoonc01/Fandom-K, pull requests merged in 2025-02, with the labels that each got.

#90 feat: #36/DonationCard 컴포넌트와 DonationModalContent 연결
  src/main.jsx
  src/pages/listPage/DonationCard.jsx
  src/pages/listPage/DonationModalContent.jsx
  src/pages/listPage/DonationsList.jsx
  src/pages/listPage/ListPage.jsx
Labels: enhancement

#93 fix: #92/Vercel 배포 중 오류로 인해 파일명 수정
  src/assets/icons/credit.svg
  src/assets/icons/creditNoFeather.svg
  src/assets/icons/fandomKLogo.svg
  src/pages/landingPage/LandingPage.jsx
  src/pages/listPage/DonationModalContent.jsx
  src/pages/listPage/ListPage.jsx
  src/utils/creditStorage.js
Labels: fix

#94 feat: #37/ 후원 모달 기능 추가
  src/apis/donationApi.js
  src/components/PrimaryButton.jsx
  src/pages/listPage/DonationCard.jsx
  src/pages/listPage/DonationModalContent.jsx
  src/pages/listPage/DonationSuccess.jsx
  src/pages/listPage/ListPage.jsx
Labels: enhancement

#95 Feat/#17/layout main section
  src/assets/images/introSectionIdolImage.png
  src/assets/images/introSectionIdolImage.webp
  src/assets/images/leftTopGradient.png
  src/assets/images/mainSectionBackgroundImage1.webp
  src/assets/images/mainSectionBackgroundImage2.webp
  src/assets/images/mainSectionBackgroundImage3.webp
  src/assets/images/mainSectionPhoneImage1.png
  src/assets/images/mainSectionPhoneImage2.png
  src/assets/images/mainSectionPhoneImage3.png
  src/pages/landingPage/IntroSection.jsx
  src/pages/landingPage/LandingPage.jsx
  src/pages/landingPage/MainSectionList.jsx
  tailwind.config.js
Labels: enhancement

#97 docs: Add tech stack and deployment URL to README
  README.md
Labels: documentation

#103 fix: #102/라우팅을 통해 바뀐 주소에서 새로고침 시 404에러 발생
  vercel.json
Labels: fix

#106 feat: #105/ 사이트 개선
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/assets/icons/favicon.ico
  src/pages/landingPage/LandingPage.jsx
  src/pages/listPage/ListPage.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/notFoundPage/NotFoundPage.jsx
Labels: enhancement

#128 refactor: #112/후원 파트 오류 처리 리팩토링
  src/apis/donationApi.js
  src/pages/listPage/DonationModalContent.jsx
  src/pages/listPage/DonationsList.jsx
Labels: enhancement

#135 Feat/#134/chaged list page directory structure
  README.md
  src/components/modalContent/CreditRechargeSuccess.jsx
  src/components/modalContent/CreditShortageModalContent.jsx
  src/components/modalContent/DonationModalContent.jsx
  src/components/modalContent/DonationSuccess.jsx
  src/components/modalContent/RechargeModalContent.jsx
  src/pages/listPage/ListPage.jsx
  src/pages/listPage/credit/CreditSection.jsx
  src/pages/listPage/donation/DonationCard.jsx
  src/pages/listPage/donation/DonationsList.jsx
  src/pages/listPage/monthlyChart/MonthlyChartItem.jsx
  src/pages/listPage/monthlyChart/MonthlyChartList.jsx
  src/pages/listPage/monthlyChart/MonthlyChartSection.jsx
Labels: enhancement

#142 Feat: #141/lighthouse 피드백 적용
  index.html
  src/assets/images/leftTopGradient.webp
  src/assets/images/mainSectionPhoneImage1.webp
  src/assets/images/mainSectionPhoneImage2.webp
  src/assets/images/mainSectionPhoneImage3.webp
  src/pages/landingPage/IntroSection.jsx
  src/pages/landingPage/LandingPage.jsx
  src/pages/landingPage/MainSectionList.jsx
  src/pages/listPage/ListPage.jsx
Labels: enhancement

#147 feat: #145/후원 모달에서 put 리퀘스트 보낸 후 바로 리렌더링
  src/pages/listPage/ListPage.jsx
  src/pages/listPage/donation/DonationsList.jsx
Labels: enhancement

#150 Feat/#22/add animation in landing page
  index.html
  src/components/FadeInDiv.css
  src/components/FadeInDiv.jsx
  src/index.css
  src/pages/landingPage/IntroSection.jsx
  src/pages/landingPage/LandingPage.jsx
  src/pages/landingPage/MainSectionList.jsx
Labels: enhancement
